#!/bin/sh
#


umask 077

PIDFILE=/var/run/gwctrl.pid

start() {
        printf "Starting Gateway Control: "
	start-stop-daemon -S -b -p $PIDFILE -m -a /bin/sh -- -c """gwctrl -h espressobin1 -i bbbgw01 | logger"""
        echo "OK"
}
stop() {
        printf "Stopping Gateway Control: "
        start-stop-daemon -K -p $PIDFILE
	echo "OK"
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
