#!/bin/sh
#


umask 077

PIDFILE=/var/run/pktfwdbr.pid

start() {
        printf "Starting Packet Forwarder Bridge: "
	start-stop-daemon -S -b -p $PIDFILE -m -a /bin/sh -- -c """pktfwdbr -h espressobin1 | logger"""
        echo "OK"
}
stop() {
        printf "Stopping Packet Forwarder Bridge: "
        start-stop-daemon -K -p $PIDFILE
	echo "OK"
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
